namespace sprites.food {
    //% fixedInstance jres blockIdentity=images._image
    //% tags="food"
    export const smallBurger = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="food"
    export const smallApple = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="food"
    export const smallLemon = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="food"
    export const smallDrumstick = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="food"
    export const smallHam = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="food"
    export const smallPizza = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="food"
    export const smallDonut = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="food"
    export const smallCake = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="food"
    export const smallIceCream = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="food"
    export const smallStrawberry = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="food"
    export const smallCherries = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="food"
    export const smallTaco = image.ofBuffer(hex``);
}
