namespace sprites.skillmap {
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals"
    export const akita = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const bridge = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const button = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cloud = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const decoration14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const fans = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile misc"
    export const islandTile0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile misc"
    export const islandTile1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile misc"
    export const islandTile2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile misc"
    export const islandTile3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile misc"
    export const islandTile4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile misc"
    export const islandTile5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile misc"
    export const islandTile6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile misc"
    export const islandTile7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile misc"
    export const islandTile8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const kaijuIcon = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mailboxIcon = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals"
    export const pigeon = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals"
    export const pigeonIcon = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const potion14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const seasonalTree0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const seasonalTree1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const seasonalTree2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const seasonalTree3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const stageIcon = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const writer = image.ofBuffer(hex``);
}
