namespace sprites.dialog {
    //% fixedInstance jres blockIdentity=images._image
    export const hugeLeaf = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const largeShell = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const largeStar = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mediumStar = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mediumShell = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mediumLeaf0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mediumLeaf1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallIndustrial0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallIndustrial1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallBlue0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallBlue1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallDefault = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallSwirlyWhite = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallSwirlyPurple = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallDialogLeftThin = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallDialogLeftThick = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallDialogCenterThin = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallDialogcenterThick = image.ofBuffer(hex``);
}
