namespace sprites.builtin {
    //% fixedInstance jres blockIdentity=images._image
    //% tags="aquatic animals"
    export const angelFish0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="aquatic animals"
    export const angelFish1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="aquatic animals"
    export const angelFish2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="aquatic animals"
    export const angelFish3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const aquaticBackground = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const bed0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const bed1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const bed2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="electronics"
    export const bigButtonPress0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="electronics"
    export const bigButtonPress1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const brick = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals"
    export const cat0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals"
    export const cat1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals"
    export const cat2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const clam0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const clam1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const clam2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const clownFish0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const clownFish1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const clownFish2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const clownFish3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const coin0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const coin1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const coin2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const coin3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const coin4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const coin5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="electronics"
    export const computer0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="electronics"
    export const computer1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="electronics"
    export const console = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile aquatic"
    export const coral0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile aquatic"
    export const coral1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile aquatic"
    export const coral2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile aquatic"
    export const coral3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile aquatic"
    export const coral4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile aquatic"
    export const coral5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const couchFront0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const couchFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const couchSide0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const couchSide1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const couchSide2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const crowd0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const crowd1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const crowd2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const crowd3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const crowd4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const crowd5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const crowd6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const crowd7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const crowd8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const crowd9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals"
    export const dog0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals"
    export const dog1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals"
    export const dog2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const field0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const field1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports"
    export const fieldGoal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports"
    export const football1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports"
    export const football2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports"
    export const football3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports"
    export const football4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports"
    export const football6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports"
    export const football7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports people"
    export const footballPlayer0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports people"
    export const footballPlayer1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports people"
    export const footballPlayer2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports people"
    export const footballPlayer3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports people"
    export const footballPlayer4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports people"
    export const footballPlayer5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports people"
    export const footballPlayer6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="sports people"
    export const footballPlayer7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const forestBackground = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals dungeon"
    export const forestBat0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals dungeon"
    export const forestBat1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals dungeon"
    export const forestBat2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals dungeon"
    export const forestBat3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals dungeon"
    export const forestBat4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals dungeon"
    export const forestBat5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals dungeon"
    export const forestBat6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals dungeon"
    export const forestBat7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestFlowers0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestFlowers1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestFlowers2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestLargeMushroom0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestLargeMushroom1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestMonkey0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestMonkey1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestMonkey2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestMonkey3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestMonkey4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestMonkey5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestMonkey6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestMonkey7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestMonkey8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestMonkey9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestMonkey10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestMushroomPatch = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestScenery0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestScenery1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestScenery2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestScenery3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestSnake0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestSnake1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestSnake2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestSnake3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestSnake4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestSnake5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestSnake6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals forest"
    export const forestSnake7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles19 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles20 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles25 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles26 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles27 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles28 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile forest"
    export const forestTiles29 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestTree0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestTree1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestTree2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestTree3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestTreeGroup0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestTreeGroup1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestTreeGroup2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestTreeGroup3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="forest"
    export const forestTreeGroup4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const furnitureRug = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const furnitureTable1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const furnitureTable2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabAttack0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabAttack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabAttack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabAttack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabAttack4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabAttack5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabAwaken0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabAwaken1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabAwaken2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabAwaken3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabAwaken4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabAwaken5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabWalk0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabWalk1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabWalk2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const hermitCrabWalk3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="aquatic"
    export const largeOceanRock = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const largeShelf = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="aquatic"
    export const mediumOceanRock = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanDepths0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanDepths1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanDepths2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanDepths3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanDepths4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanDepths5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanDepths6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanDepths7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanDepths8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanDepths9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanDepths10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanDepths11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile aquatic"
    export const oceanSand15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const pedestal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="aquatic"
    export const seaweed0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="aquatic"
    export const seaweed1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="aquatic"
    export const seaweed2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const shark0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const shark1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const shark2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const shark3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const sharkAttack0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const sharkAttack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const sharkAttack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const sharkAttack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const sharkAttack4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="animals aquatic"
    export const sharkAttack5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="aquatic"
    export const smallOceanRock = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const smallShelf0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const smallShelf1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="furniture"
    export const smallShelf2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="electronics"
    export const tv = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager1WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager1WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager1WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager1WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager1WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager1WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager1WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager1WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager1WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager1WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager1WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager1WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager2WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager2WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager2WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager2WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager2WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager2WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager2WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager2WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager2WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager2WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager2WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager2WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager3WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager3WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager3WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager3WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager3WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager3WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager3WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager3WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager3WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager3WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager3WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager3WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager4WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager4WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager4WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager4WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager4WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager4WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager4WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager4WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager4WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="people"
    export const villager4WalkRight2 = image.ofBuffer(hex``);
}
