namespace sprites.vehicle {
    //% fixedInstance jres blockIdentity=images._image
    export const carRedLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const carRedRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const carRedBack = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const carRedFront = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const carBlueLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const carBlueRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const carBlueBack = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const carBlueFront = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const carPinkLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const carPinkRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const carPinkBack = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const carPinkFront = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-Road"
    export const roadTurn1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-Road"
    export const roadTurn2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-Road"
    export const roadIntersection1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-Road"
    export const roadIntersection2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-Road"
    export const roadTurn3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-Road"
    export const roadTurn4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-Road"
    export const roadIntersection3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-Road"
    export const roadIntersection4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-Road"
    export const roadVertical = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-Road"
    export const roadHorizontal = image.ofBuffer(hex``);
}
