namespace sprites.background {
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const autumn = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const cityscape = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const cityscape2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const desert = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const forest1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const forest2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const fossils = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const lanterns = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const lilypads = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const lunarnewyear = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const moon = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const snowynight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const stage = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const starryclouds = image.ofBuffer(hex``);
}
