namespace sprites.dialog {
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const bones = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const cityscape = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const desert = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const frogs = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const hugeLeaf = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const largeShell = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const largeStar = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const mediumStar = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const mediumShell = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const mediumLeaf0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const mediumLeaf1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const pineday = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const pinenight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const smallIndustrial0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const smallIndustrial1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const smallBlue0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const smallBlue1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const smallDefault = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const smallSwirlyWhite = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const smallSwirlyPurple = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const smallDialogLeftThin = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const smallDialogLeftThick = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const smallDialogCenterThin = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const smallDialogcenterThick = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dialog"
    export const starryclouds = image.ofBuffer(hex``);
}
