namespace sprites.builtin {
    //% fixedInstance jres blockIdentity=images._image
    export const bed0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const bed1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const bed2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const brick = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cat0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cat1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cat2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const computer0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const computer1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const console = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchFront0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchSide0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchSide1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchSide2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const dog0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const dog1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const dog2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const field0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const field1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const fieldGoal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const football1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const football2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const football3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const football4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const football6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const football7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerThrowing0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerThrowing1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerThrowing2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerThrowing3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerThrowing4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerThrowing5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const furnitureRug = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const furnitureTable1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const furnitureTable2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const largeShelf = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallShelf0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallShelf1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallShelf2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tv = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkRight2 = image.ofBuffer(hex``);
}
