namespace sprites.builtin {
    //% fixedInstance jres blockIdentity=images._image
    export const angelFish0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const angelFish1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const angelFish2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const angelFish3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const bed0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const bed1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const bed2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const brick = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cat0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cat1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cat2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const clam0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const clam1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const clam2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const clownFish0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const clownFish1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const clownFish2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const clownFish3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const coin0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const coin1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const coin2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const coin3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const coin4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const coin5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const computer0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const computer1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const console = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const coral0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const coral1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const coral2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const coral3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const coral4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const coral5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchFront0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchSide0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchSide1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchSide2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const crowd9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const dog0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const dog1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const dog2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const field0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const field1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const fieldGoal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const football1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const football2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const football3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const football4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const football6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const football7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayer11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerCheer0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerCheer1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerCheer2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerCheer3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerCheer4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerCheer5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerCheer6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerCheer7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerCheer8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerCheer9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerCheer10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerCheer11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerCheer12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerCheer13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerDance0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerDance1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerDance2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerDance3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerDance4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerDance5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerDance6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerSpin0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerSpin1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerSpin2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerSpin3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerSpin4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerSpin5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerSpin6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerSpin7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerThrowing0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerThrowing1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerThrowing2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerThrowing3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerThrowing4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const footballPlayerThrowing5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const furnitureRug = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const furnitureTable1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const furnitureTable2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabAttack0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabAttack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabAttack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabAttack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabAttack4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabAttack5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabAwaken0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabAwaken1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabAwaken2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabAwaken3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabAwaken4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabAwaken5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabWalk0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabWalk1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabWalk2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const hermitCrabWalk3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const largeOceanRock = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const largeShelf = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const mediumOceanRock = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanDepths0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanDepths1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanDepths2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanDepths3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanDepths4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanDepths5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanDepths6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanDepths7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanDepths8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanDepths9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanDepths10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanDepths11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const oceanSand15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const seaweed0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const seaweed1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const seaweed2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const shark0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const shark1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const shark2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const shark3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const sharkAttack0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const sharkAttack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const sharkAttack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const sharkAttack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const sharkAttack4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const sharkAttack5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallOceanRock = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallShelf0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallShelf1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallShelf2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tv = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager1WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager2WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager3WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const villager4WalkRight2 = image.ofBuffer(hex``);
}
