namespace sprites.space {
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceSmallAsteroid0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceSmallAsteroid1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceSmallAsteroid2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceSmallAsteroid3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceAsteroid0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceAsteroid1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceSmallAsteroid4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceSmallAsteroid5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceRedShip = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceAsteroid2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceAsteroid3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceAsteroid4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceOrangeShip = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spacePinkShip = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceBlueShip = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const spaceGreenShip = image.ofBuffer(hex``);
}
