namespace sprites.dungeon {
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile electronics"
    export const buttonOrange = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile electronics"
    export const buttonOrangeDepressed = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile electronics"
    export const buttonTeal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile electronics"
    export const buttonTealDepressed = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile electronics"
    export const buttonPink = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile electronics"
    export const buttonPinkDepressed = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile dungeon"
    export const chestClosed = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile dungeon"
    export const chestOpen = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile dungeon"
    export const collectibleInsignia = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile dungeon"
    export const collectibleRedCrystal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile dungeon"
    export const collectibleBlueCrystal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const darkGroundNorthWest0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const darkGroundNorth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const darkGroundNorthEast0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const darkGroundNorthWest1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const darkGroundWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const darkGroundCenter = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const darkGroundEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const darkGroundNorthEast1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const darkGroundSouthWest0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const darkGroundSouth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const darkGroundSouthEast0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const darkGroundSouthEast1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const darkGroundSouthWest1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const doorClosedWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const doorClosedSouth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const doorClosedNorth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const doorClosedEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const doorOpenWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const doorOpenSouth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const doorOpenNorth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const doorOpenEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const doorLockedWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const doorLockedSouth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const doorLockedNorth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const doorLockedEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorLight0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorLight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorLight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorLightMoss = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorLight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorLight4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorLight5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorMixed = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorDark0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorDark1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorDark2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorDarkDiamond = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorDark3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorDark4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const floorDark5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterNorthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterNorth0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterNorth1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterNorthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterWest0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenInnerNorthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenInnerNorthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterEast0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterWest1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenInnerSouthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenInnerSouthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterEast1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterSouthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterSouth0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterSouth1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterSouthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterNorth2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterEast2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterSouth2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenOuterWest2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenSwitchUp = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const greenSwitchDown = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const hazardWater = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const hazardLava0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const hazardLava1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const hazardHole = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const hazardSpike = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterNorthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterNorth0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterNorth1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterNorthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterWest0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleInnerNorthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleInnerNorthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterEast0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterWest1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleInnerSouthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleInnerSouthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterEast1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterSouthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterSouth0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterSouth1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterSouthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterNorth2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterEast2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterSouth2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleOuterWest2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleSwitchUp = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const purpleSwitchDown = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const stairWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const stairSouth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const stairNorth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const stairEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const stairLarge = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile dungeon"
    export const stairLadder = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dungeon"
    export const statueLight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="dungeon"
    export const statueDark = image.ofBuffer(hex``);
}
