namespace sprites.kaiju {
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const egg = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const eggRolling = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const kaijuBabyLarge = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuBabyWalk0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuBabyWalk1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuBabyWalk2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuBabyWalk3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuBabyWalk4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuBabyWalk5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuMomAttack0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuMomAttack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuMomAttack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuMomAttack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuMomAttack4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuMomAttack5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const kaijuMomLarge = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuMomWalk0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuMomWalk1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuMomWalk2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuMomWalk3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuMomWalk4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc misc"
    export const kaijuMomWalk5 = image.ofBuffer(hex``);
}
