namespace sprites.vehicle {
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const carRedLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const carRedRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const carRedBack = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const carRedFront = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const carBlueLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const carBlueRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const carBlueBack = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const carBlueFront = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const carPinkLeft = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const carPinkRight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const carPinkBack = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const carPinkFront = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const car20 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const car21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const car22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const car23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const car30 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const car31 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const car32 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const car33 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const plane0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const plane1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const plane2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const plane3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const plane4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const plane5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const roadTurn1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const roadTurn2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const roadIntersection1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const roadIntersection2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const roadTurn3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const roadTurn4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const roadIntersection3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const roadIntersection4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const roadVertical = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile misc"
    export const roadHorizontal = image.ofBuffer(hex``);
}
