namespace sprites.dungeon {
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const buttonOrange = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const buttonOrangeDepressed = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const buttonTeal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const buttonTealDepressed = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const buttonPink = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const buttonPinkDepressed = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const chestClosed = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const chestOpen = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const collectibleInsignia = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const collectibleRedCrystal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="?tile"
    export const collectibleBlueCrystal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const darkGround14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const doorClosedWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const doorClosedSouth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const doorClosedNorth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const doorClosedEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const doorOpenWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const doorOpenSouth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const doorOpenNorth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const doorOpenEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const doorLockedWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const doorLockedSouth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const doorLockedNorth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const doorLockedEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorLight0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorLight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorLight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorLight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorLight4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorLight5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorDark0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorDark1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorDark2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorDark3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorDark4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorDark5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorDarkDiamond = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorLightMoss = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const floorMixed = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterNorthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterNorth0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterNorth1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterNorth2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterNorthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterEast0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterEast1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterEast2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterSouthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterSouth0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterSouth1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterSouth2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterSouthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterWest0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterWest1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenOuterWest2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenSwitchUp = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const greenSwitchDown = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const green_innerNorthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const green_innerNorthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const green_innerSouthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const green_innerSouthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const hazardWater = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const hazardLava0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const hazardLava1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const hazardHole = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const hazardSpike = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterNorthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterNorth0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterNorth1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterNorth2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterNorthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterEast0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterEast1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterEast2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterSouthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterSouth0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterSouth1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterSouth2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterSouthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterWest0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterWest1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleOuterWest2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleSwitchUp = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purpleSwitchDown = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purple_innerNorthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purple_innerNorthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purple_innerSouthEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const purple_innerSouthWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const stairWest = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const stairSouth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const stairNorth = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const stairEast = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const stairLarge = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const stairLadder = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const statueLight = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const statueDark = image.ofBuffer(hex``);
}
