namespace sprites.projectile {
    //% fixedInstance jres blockIdentity=images._image
    //% tags="aquatic"
    export const bubble1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="aquatic"
    export const bubble2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="aquatic"
    export const bubble3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="aquatic"
    export const bubble4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const drop1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const drop2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const drop3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const drop4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const drop5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const explosion1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const explosion2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const explosion3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const explosion4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const firework1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const firework2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const firework3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const firework4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const firework5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const flash1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const flash2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const flash3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const heart1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const heart2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const heart3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const heart4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const heart5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const laser1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const laser2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const laser3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const laser4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const star1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const star2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const star3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const star4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const star5 = image.ofBuffer(hex``);
}
