namespace sprites.castle {
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkFront4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkBack4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldFront4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldBack4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldSideLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldSideLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldSideLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldSideLeft4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldSideRight4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldSideRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldSideRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkShieldSideRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkSideLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkSideLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkSideLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkSideLeft4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkSideRight4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkSideRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkSideRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroWalkSideRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroFrontAttack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroFrontAttack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroFrontAttack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroFrontAttack4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroSideAttackLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroSideAttackLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroSideAttackLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroSideAttackLeft4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroSideAttackRight4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroSideAttackRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroSideAttackRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const heroSideAttackRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princessFront0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princessFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princessFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princessLeft0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princessLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princessLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princessBack0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princessBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princessBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princess2Front = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princess2WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princess2WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princess2WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princess2Back = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princess2WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princess2WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princess2WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princess2Left1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princess2Left2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princess2Right1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const princess2Right2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const houseRed = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const houseBlue = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const rock0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const rock1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const rock2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const saplingOak = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const saplingPine = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const shrub = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyFront = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyWalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyWalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyWalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyAttackFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyAttackFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyAttackFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyAttackFront4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyWalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyAttackLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyAttackLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyWalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyWalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyAttackRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyAttackRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const skellyWalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tileGrass1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tileGrass2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tilePath1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tilePath2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tilePath3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tileDarkGrass1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tileDarkGrass2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tilePath4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tilePath5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tilePath6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tileGrass3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tileDarkGrass3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tilePath7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tilePath8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tilePath9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const treePine = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const treeOak = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const treeSmallPine = image.ofBuffer(hex``);
}
