namespace sprites.city {
    //% fixedInstance jres blockIdentity=images._image
    export const bed0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const bed1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const bed2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="tile"
    export const brick = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cat0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cat1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const cat2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen1WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen1WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen1WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen1WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen1WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen1WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen1WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen1WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen1WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen1WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen1WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen1WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen2WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen2WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen2WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen2WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen2WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen2WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen2WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen2WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen2WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen2WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen2WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen2WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen3WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen3WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen3WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen3WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen3WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen3WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen3WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen3WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen3WalkLeft3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen3WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen3WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen3WalkRight3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen4WalkFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen4WalkFront2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen4WalkFront3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen4WalkBack1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen4WalkBack2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen4WalkBack3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen4WalkLeft1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen4WalkLeft2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen4WalkRight1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const citizen4WalkRight2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const computer0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const computer1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const console = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchFront0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchFront1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchSide0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchSide1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const couchSide2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const dog0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const dog1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const dog2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const furnitureRug = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const furnitureTable1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const furnitureTable2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const largeShelf = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallShelf0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallShelf1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const smallShelf2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    export const tv = image.ofBuffer(hex``);
}
