namespace storySprites {
    //% fixedInstance jres blockIdentity=images._image
    //% tags="misc"
    export const mistletoe = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const halloween = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const holiday = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const holiday2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const birthday = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const world = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const field = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const valentines = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const lake = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const ocean = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const sky = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const castle = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._image
    //% tags="background"
    export const castle2 = image.ofBuffer(hex``);

}