name: playlists

on:
  schedule:
    - cron:  '30 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          sudo npm install -g pxt
          npm install
      - name: updated playlists
        run: |
          pxt downloadplaylists
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: Updated playlists
          branch: playlists/patch
          title: 'Updated playlists'
